import os

REMOTE_DBG_HOST = os.environ.get("PYTHON_REMOTE_DBG_HOST", "0.0.0.0")
REMOTE_DBG_PORT = int(os.environ.get("PYTHON_REMOTE_DBG_PORT", 7200))

REMOTE_DBG_EVENTS_FILE = "/tmp/remote-debugger-events.log"
REMOTE_DBG_EVENTS_FILE_LOCKFILE = "{}.lockfile".format(REMOTE_DBG_EVENTS_FILE)

REMOTE_DBG_EVENT_TYPE_STARTING_DEBUG_SESSION = "STARTING_DEBUG_SESSION"

REMOTE_DBG_DEBUGGER_TYPE_REMOTE = "REMOTE"
REMOTE_DBG_DEBUGGER_TYPE_WEB = "WEB"
